### ISSUE TITLE
Bikes still in register as 1-minute stays

### ISSUE THREAD

**Issue by ironwoodcall** [ironwoodcall/TagTracker#149] opened 2023-06-05 02:28 UTC
Shortest stay is accordingly often taken up by bikes that are still at the valet which makes it not as useful

**Comment by tevpg** [comment] 2023-06-05 02:46
This surprises me, that's certainly not the logic I intended.  If I recall correctly, my intention was that bikes-still-in were treated as if they had gone out as of the later of latest event of day or closing time.

Let me check it out (so to speak)

**Comment by tevpg** [comment] 2023-06-05 02:51
Confirmed that able to reproduce the problem:
```
TagTracker 0.8.0 by Julias Hocking
  
  Creating new datafile logs/cityhall_2023-06-04.log.
  No inconsistencies found
  
  Please enter today's opening/closing times.
  
  Bike Valet information for Sunday June 04 (2023-06-04)
  New valet opening time (24 hour clock HHMM or <Enter> to cancel) >>>   1000
  Opening time now set to 10:00
  New valet closing time (24 hour clock HHMM or <Enter> to cancel) >>>   1800
  Closing time now set to 18:00
  
               ╭──────────╮             
     FREE      │ 🚲🚲🛴🚲 │     BIKE    
     SAFE     🔒 🚲🚲🚲🛴 │     VALET   
               ╰──────────╯             
  
  
  19:49  Bike tag or command >>>   wa1
  Bike WA1 checked IN                      <---in---  
  
  19:49  Bike tag or command >>>   e wa1 i 1100
  Bike WA1 checked IN at 11:00             <---in---  
  
  19:49  Bike tag or command >>>   a
  
  Audit report as at 19:50
  
  Summary             Regular Oversize Total
  Bikes checked in:        1       0       1
  Bikes returned out:      0       0       0
  Bikes in valet:          1       0       1
  
  Bikes still in valet at 19:50
  WA     01
  
  Bikes returned out (0 Total)
  -no bikes-
  
  19:50  Bike tag or command >>>   f
  
  Tracking form data from start of day until 19:59
  
  Bikes checked IN
  ----------------
  11:00-11:29 <<<< WA1 
  
  Bikes returned OUT
  ------------------
  11:00-11:29 >>>>  
  
  19:50  Bike tag or command >>>   s
  
  Summary statistics as at 19:50
  
  Bike check-ins
  Total bikes in:      1
  AM bikes in:         1
  PM bikes in:         0
  Regular in:          1
  Oversize in:         0
  Bikes still here:    1
  
  Number of stays by duration
  Stays < 1.5h:        1
  Stays 1.5-5.0h:      0
  Stays >= 5.0h:       0
  
  Stay-length statistics
  Longest stay:     0:01  (tag: WA1)
  Shortest stay:    0:01  (tag: WA1)
  Mean stay:        0:01
  Median stay:      0:01
  Mode stay:        0:00  (times rounded to 30 minutes)
  
  19:50  Bike tag or command >>>   x
```

**Comment by tevpg** [comment] 2023-06-05 03:36
Addressed in branch https://github.com/ironwoodcall/TagTracker/tree/feat/85/reporting-publishing(2)

**Closed** 2023-06-06 03:55 UTC
Labels: bug
